name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: '20'
  FIREBASE_PROJECT_ID: 'cin-foundation'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint code
        run: npm run lint
        continue-on-error: true
      
      - name: Build project
        run: npm run build
      
      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed: dist directory not found"
            exit 1
          fi
          if [ ! -f "dist/index.html" ]; then
            echo "Build failed: index.html not found in dist"
            exit 1
          fi
          echo "Build verification successful"
      
      - name: Deploy to Firebase Hosting (Preview Channel)
        id: preview_deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CIN_FOUNDATION }}'
          projectId: ${{ env.FIREBASE_PROJECT_ID }}
          channelId: preview
          expires: 7d
        if: github.event_name == 'pull_request'
      
      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request' && steps.preview_deploy.outputs.details_url
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Preview deployment ready!**
              
              📱 **Preview URL:** ${{ steps.preview_deploy.outputs.details_url }}
              
              This preview will be available for 7 days and will be automatically cleaned up.`
            })
      
      - name: Deploy to Firebase Hosting (Production)
        id: production_deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CIN_FOUNDATION }}'
          projectId: ${{ env.FIREBASE_PROJECT_ID }}
          channelId: live
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      
      - name: Production deployment success
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.production_deploy.outputs.details_url
        run: |
          echo "🎉 Production deployment successful!"
          echo "🌐 Live URL: ${{ steps.production_deploy.outputs.details_url }}"