name: Test Deployment Configuration

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'firebase.json'
      - '.firebaserc'
      - '.github/workflows/firebase-deploy.yml'

jobs:
  test_config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Validate Firebase configuration
        run: |
          echo "Validating firebase.json..."
          firebase hosting:sites:list --project cin-foundation || echo "Note: Firebase authentication required for full validation"
          
          echo "Checking build output..."
          if [ ! -f "dist/index.html" ]; then
            echo "❌ Build failed: index.html not found"
            exit 1
          fi
          
          echo "Checking Firebase configuration files..."
          if [ ! -f "firebase.json" ]; then
            echo "❌ firebase.json not found"
            exit 1
          fi
          
          if [ ! -f ".firebaserc" ]; then
            echo "❌ .firebaserc not found"
            exit 1
          fi
          
          echo "✅ All configuration files present"
          echo "✅ Build output verified"
          echo "✅ Deployment configuration test passed"